### ISSUE TITLE
Created reusable workflow for triggering jenkins job

### ISSUE THREAD

**Issue by ppsinghcalance** [Calance-US/calance-workflows#1]
- [x] Fixed issue related to linter.
- [x] Solved issue related to accessing secrets in pipeline.
- [x] Trigger Jenkins Job.
- [x] Created reusable workflow.

**Comment by agoyalcalance** [comment]
@ppsinghcalance how can the title of an issue be bugfix? please read how to create issues in Github if you are not sure.. and put an elaborative title and description to your issue.

Also you have attached the following labels - bug and enhancement, how can an issue be a bug and enhancement at the same time? These are some logical points for which you don't even need anyone and has nothing to do with knowing stuff, correct me if I am wrong?

Even the branch name is `bugfix`??????... how difficult is it to adopt standards @ppsinghcalance ?

CC: @DLNS-calance please assist Prem in understanding how to structure issues.
