### ISSUE TITLE
creating deploy-suffix-yml file

### ISSUE THREAD

**Issue by ppsinghcalance** [Calance-US/calance-workflows#10]

**Comment by agoyalcalance** [comment]
@ppsinghcalance why was this issue created? Isn't it linked to the #8

**Comment by ppsinghcalance** [comment]
@agoyalcalance I forgot about  8# issue , that why i have created a new one.

**Comment by agoyalcalance** [comment]
@ppsinghcalance what do you mean by you forgot about that issue?
