### ISSUE TITLE
[FEATURE] [Delete all tags created during test]

### ISSUE THREAD

**Issue by agoyalcalance** [Calance-US/calance-workflows#3]
**Is your feature request related to a problem? Please describe.**
All the tags created in this repository needs to be deleted as they were created during testing

**Describe the solution you'd like**
N/A

**Additional context**
N/A

**Comment by ppsinghcalance** [comment]
Deleted all the tags

**Comment by agoyalcalance** [comment]
@ppsinghcalance closing this issue.
